import { useState } from 'react';
import { historicalSessions, type HistoryArchive } from './history';
export function ArchiveView({ archive }: { archive: HistoryArchive }) {
  const [block, setBlock] = useState('');
  const [week, setWeek] = useState('');
  const [day, setDay] = useState('');
  const [query, setQuery] = useState('');
  const [limit, setLimit] = useState(20);
  const all = historicalSessions(archive);
  const filtered = all.filter(s => (!block || s.block === Number(block)) && (!week || s.week === Number(week)) && (!day || s.day === day) && (!query || s.lines.some(l => l.text.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')))));
  return <section className="panel archive-panel"><div className="section-heading"><h2>Histórico importado</h2><span className="pill">{all.length} sesiones</span></div><p className="muted">Tus anotaciones completas, sin fechas inventadas. Las series antiguas se conservan en su formato original; todavía no alimentan las estadísticas de series ni la precarga de pesos.</p><div className="session-fields"><label>Filtrar bloque<select value={block} onChange={e => { setBlock(e.target.value); setWeek(''); setLimit(20); }}><option value="">Todos</option>{[...new Set(all.map(s => s.block))].sort((a,b)=>a-b).map(b => <option key={b}>{b}</option>)}</select></label><label>Filtrar semana<select value={week} onChange={e => { setWeek(e.target.value); setLimit(20); }}><option value="">Todas</option>{[...new Set(all.filter(s=>!block || s.block===Number(block)).map(s=>s.week))].sort((a,b)=>a-b).map(w => <option key={w}>{w}</option>)}</select></label><label>Filtrar día<select value={day} onChange={e=>{setDay(e.target.value);setLimit(20);}}><option value="">Todos</option>{['A','B','C','Brazos'].map(d=><option key={d}>{d}</option>)}</select></label></div><label>Buscar ejercicio o anotación<input value={query} onChange={e=>{setQuery(e.target.value);setLimit(20);}} placeholder="Ej. prensa, 39kg, cluster…" /></label><p className="small-note">{filtered.length} sesiones encontradas. Los días y semanas ausentes no se añaden.</p>{filtered.slice(0,limit).map(s=><details className="archive-session" key={s.id}><summary>Bloque {s.block} · Semana {s.week} · {s.day === 'Brazos' ? 'Brazos' : `Día ${s.day}`}</summary><p className="small-note">{s.source} · fecha sin anotar</p>{s.lines.map(l=><div className="archive-line" key={l.number}>{l.warning && <p className="inline-error">{l.warning}</p>}<p>{l.text}</p></div>)}</details>)}{filtered.length>limit && <button className="secondary" onClick={()=>setLimit(limit+20)}>Mostrar 20 más</button>}</section>;
}
