import { useMemo, useState } from 'react';
import type { Data } from './model';
import { attendance, defaultCalendar, extractStatistics, monday, performanceDate, record, weekDate, weekRange, type CalendarConfig, type Performance } from './statistics';
const n=(v:number)=>v.toLocaleString('es-ES',{maximumFractionDigits:2});
const generalKey=(r:Performance)=>`${r.exercise}|${r.unit}|${r.convention}|general`;
const label=(r:Performance)=>`B${r.block} / S${r.week} · ${r.day}`;
export function StatisticsView({data,save}:{data:Data;save:(data:Data)=>void}) {
  const calendar=data.calendar??defaultCalendar(data);
  const extracted=useMemo(()=>extractStatistics(data),[data.history,data.sessions]);
  const [blockFilter,setBlockFilter]=useState('');
  const blocks=[...new Set(extracted.performances.map(r=>r.block))].sort((a,b)=>a-b);
  const filtered=extracted.performances.filter(r=>!blockFilter||r.block===Number(blockFilter));
  const names=[...new Set(filtered.map(r=>r.exercise))].sort((a,b)=>a.localeCompare(b,'es'));
  const [choice,setChoice]=useState('');
  const name=names.includes(choice)?choice:names[0]??'';
  const exerciseRows=filtered.filter(r=>r.exercise===name);
  const generalGroups=[...new Map(exerciseRows.map(r=>[generalKey(r),{...r,group:generalKey(r),scope:'General · todos los equipos'}])).values()];
  const groups=[...generalGroups,...new Map(exerciseRows.map(r=>[r.group,r])).values()];
  const [groupChoice,setGroupChoice]=useState('');
  const group=groups.some(r=>r.group===groupChoice)?groupChoice:groups[0]?.group??'';
  const rows=exerciseRows.filter(r=>(r.group===group||generalKey(r)===group)&&r.reps>0).sort((a,b)=>performanceDate(a,calendar).localeCompare(performanceDate(b,calendar)));
  const best=record(rows);
  const currentMonday=monday(new Date().toISOString().slice(0,10));
  const recent=record(rows.filter(r=>{const age=Date.parse(currentMonday)-Date.parse(performanceDate(r,calendar));return age>=0&&age<4*7*86400000;}));
  const [weightChoice,setWeightChoice]=useState('');
  const loads=[...new Set(rows.map(r=>r.weight))].sort((a,b)=>(b??-1)-(a??-1));
  const requested=weightChoice==='null'?null:Number(weightChoice);
  const weight=loads.includes(requested)&&weightChoice!==''?requested:best?.weight??null;
  const fixed=rows.filter(r=>r.weight===weight);
  const weekly=(values:Performance[],metric:'weight'|'reps')=>[...new Map(values.map(r=>[performanceDate(r,calendar),r])).keys()].map(key=>{const candidates=values.filter(r=>performanceDate(r,calendar)===key);return [...candidates].sort((a,b)=>(b[metric]??-1)-(a[metric]??-1)||b.reps-a.reps)[0];});
  const allRecords=[...new Map(filtered.map(r=>[generalKey(r),r])).keys()].map(g=>record(filtered.filter(r=>generalKey(r)===g))).filter((r):r is Performance=>!!r).sort((a,b)=>a.exercise.localeCompare(b.exercise,'es'));
  const weeks=attendance(data,calendar).filter(r=>!blockFilter||r.block===Number(blockFilter));
  const past=weeks.filter(w=>w.date<monday(new Date().toISOString().slice(0,10)));
  const completed=past.filter(w=>w.count===4).length;
  const [draft,setDraft]=useState<CalendarConfig>(calendar);
  const [reviewLimit,setReviewLimit]=useState(20);
  const [calendarError,setCalendarError]=useState('');
  const saveCalendar=()=>{
    if (!/^\d{4}-\d{2}-\d{2}$/.test(draft.anchorDate)||Number.isNaN(Date.parse(draft.anchorDate))||!Number.isInteger(draft.block)||draft.block<1||draft.block>99||!Number.isInteger(draft.week)||draft.week<1||draft.week>104||Object.values(draft.lengths).some(v=>!Number.isInteger(v)||v<1||v>104)||draft.week>(draft.lengths[draft.block]??104)) {setCalendarError('Revisa la fecha, la semana y la duración de los bloques.');return;}
    setCalendarError('');save({...data,calendar:{...draft,anchorDate:monday(draft.anchorDate)}});
  };
  return <div className="statistics-view">
    <section className="panel"><div className="section-heading"><h2>Marcas y evolución</h2><span className="pill">{allRecords.length} comparaciones</span></div><p className="muted">Mayor carga con repeticiones completas registradas. Cada marca conserva sus repeticiones, RIR y fuente. No se suman los lados ni las parciales. La vista general reúne todos los bloques. Puedes filtrar un bloque o un equipo. Las marcas de máquinas sin identificar son provisionales: sus cargas pueden no ser equivalentes.</p>
      <div className="stats-filters"><label>Periodo<select aria-label="Periodo" value={blockFilter} onChange={e=>{setBlockFilter(e.target.value);setGroupChoice('');setWeightChoice('');}}><option value="">Todo mi historial</option>{blocks.map(b=><option key={b} value={b}>Bloque {b}</option>)}</select></label></div>
      {!names.length?<p>Importa tu histórico o completa series para ver tus marcas.</p>:<><div className="stats-filters"><label>Ejercicio<select aria-label="Ejercicio" value={name} onChange={e=>{setChoice(e.target.value);setGroupChoice('');setWeightChoice('');}}>{names.map(v=><option key={v}>{v}</option>)}</select></label><label>Variante, equipo y unidad<select aria-label="Variante, equipo y unidad" value={group} onChange={e=>{setGroupChoice(e.target.value);setWeightChoice('');}}>{groups.map(r=><option key={r.group} value={r.group}>{r.scope} · {r.convention} · {r.unit}</option>)}</select></label></div>
      <div className="stats-cards"><Mark title={blockFilter?`Récord del bloque ${blockFilter}`:"Récord histórico"} value={best} calendar={calendar}/><Mark title="Mejor en las últimas 4 semanas" value={recent} calendar={calendar}/><div className="info-box"><strong>Hasta tu récord</strong><p>{best&&recent&&best.scope!==recent.scope ? 'Equipos distintos o sin confirmar: las cargas no permiten una comparación directa.' : best&&recent&&best.weight!==null&&recent.weight!==null ? recent.weight===best.weight ? `Misma carga · ${Math.max(0,best.reps-recent.reps)} repeticiones hasta tu mejor serie con esa carga` : `${n(best.weight-recent.weight)} ${best.unit} de diferencia en carga` : 'Sin una serie comparable en las últimas 4 semanas.'}</p><p className="small-note">Unidades y convenciones de carga se mantienen separadas.</p></div></div>
      <SeriesChart rows={weekly(rows.filter(r=>r.weight!==null),'weight')} metric="weight" calendar={calendar} title="Carga máxima registrada por semana"/>
      <label className="stats-load">Comparar repeticiones con esta carga<select aria-label="Comparar repeticiones con esta carga" value={String(weight)} onChange={e=>setWeightChoice(e.target.value)}>{loads.map(v=><option key={String(v)} value={String(v)}>{v===null?'Carga sin anotar':`${n(v)} ${best?.unit}`}</option>)}</select></label>
      <SeriesChart rows={weekly(fixed,'reps')} metric="reps" calendar={calendar} title="Mejores repeticiones con la misma carga"/>
      <details><summary>Mejor serie con cada peso</summary><div className="stats-table">{loads.map(load=>{const r=[...rows].filter(r=>r.weight===load).sort((a,b)=>b.reps-a.reps)[0];return <div className="stat-row" key={String(load)}><strong>{load===null?'Carga sin anotar':`${n(load)} ${r.unit}`} × {r.reps}</strong><span>RIR {r.rir||'sin anotar'} · {label(r)}</span></div>;})}</div></details></>}
    </section>
    <section className="panel"><h2>{blockFilter?`Marcas del bloque ${blockFilter}`:"Marcas de todo tu historial"}</h2><p className="small-note">Los pesos de máquinas distintas no son equivalentes. Pulsa una marca para ver su evolución.</p><div className="stats-table">{allRecords.map(r=><button className="stat-row" key={generalKey(r)} onClick={()=>{setChoice(r.exercise);setGroupChoice(generalKey(r));setWeightChoice('');window.scrollTo({top:0,behavior:'smooth'});}}><span><strong>{r.exercise}</strong><small>{r.convention} · {r.unit}{r.scope.includes("sin identificar")?" · equipo sin confirmar":""}</small></span><span><strong>{r.weight===null?'Carga sin anotar':`${n(r.weight)} ${r.unit}`} × {r.reps}</strong><small>RIR {r.rir||'sin anotar'} · {label(r)}</small></span></button>)}</div></section>
    <section className="panel"><div className="section-heading"><h2>Constancia en entrenos</h2><span className="pill">A → B → C → Brazos</span></div><p className="muted">Objetivo: los cuatro días de cada semana, incluido Brazos. Un día cuenta una vez aunque se importe y se registre de nuevo. Las sesiones abiertas aún no cuentan.</p><div className="stats-cards"><div className="info-box"><strong>{weeks.reduce((sum,w)=>sum+w.count,0)} entrenamientos</strong><p>Días completados distintos por bloque y semana.</p></div><div className="info-box"><strong>{completed} de {past.length} semanas completas</strong><p>{past.length?n(completed/past.length*100):'—'} % con los cuatro entrenamientos. La semana actual se evalúa cuando termina.</p></div></div><div className="attendance-grid">{[...weeks].reverse().map(w=><details key={`${w.block}-${w.week}`} className={`attendance-week level-${w.count}`}><summary><strong>B{w.block} · S{w.week}</strong><span>{w.count} / 4</span></summary><p>{weekRange(w.date)} · calendario estimado</p><p>{['A','B','C','Brazos'].map(d=>`${w.days.includes(d as 'A')?'✓':'—'} ${d}`).join(' · ')}</p></details>)}</div></section>
    <section className="panel"><h2>Calendario del histórico</h2><p className="muted">Referencia guardada: semana {calendar.week} del bloque {calendar.block}, {weekRange(monday(calendar.anchorDate))}. El cálculo retrocede por semanas, manteniendo los huecos sin entrenar. No asigna un día exacto a cada sesión.</p><p className="small-note">La duración inicial de cada bloque es su última semana anotada. Ajusta estos valores si algún bloque tuvo semanas finales sin registros.</p><div className="stats-filters"><label>Fecha dentro de la semana de referencia<input type="date" value={draft.anchorDate} onChange={e=>setDraft({...draft,anchorDate:e.target.value})}/></label><label>Bloque de referencia<input type="number" min="1" max="99" value={draft.block} onChange={e=>setDraft({...draft,block:Number(e.target.value)})}/></label><label>Semana de referencia<input type="number" min="1" max="104" value={draft.week} onChange={e=>setDraft({...draft,week:Number(e.target.value)})}/></label></div><div className="stats-filters">{Object.entries(draft.lengths).map(([b,v])=><label key={b}>Semanas del bloque {b}<input type="number" min="1" max="104" value={v} onChange={e=>setDraft({...draft,lengths:{...draft.lengths,[b]:Number(e.target.value)}})}/></label>)}</div>{calendarError&&<p role="alert">{calendarError}</p>}<button className="primary" onClick={saveCalendar}>Guardar calendario</button></section>
    <section className="panel"><details><summary>Anotaciones fuera del cálculo o con extracción parcial · {extracted.review.length}</summary><p className="small-note">Se conservan los originales. Las repeticiones aproximadas, clusters y dropsets no se mezclan con las marcas de series normales.</p>{extracted.review.slice(0,reviewLimit).map(r=><details className="review-entry" key={r.id}><summary>B{r.block} / S{r.week} · {r.day} · {r.reason}</summary><p>{r.raw}</p></details>)}{extracted.review.length>reviewLimit&&<button className="secondary" onClick={()=>setReviewLimit(reviewLimit+20)}>Mostrar 20 anotaciones más</button>}</details></section>
  </div>;
}
function Mark({title,value:r,calendar}:{title:string;value:Performance|undefined;calendar:CalendarConfig}) {
  return <div className="info-box"><p>{title}</p><strong>{r?r.weight===null?`${r.reps} reps · carga sin anotar`:`${n(r.weight)} ${r.unit} × ${r.reps}`:'Sin registro'}</strong>{r&&<><p>RIR {r.rir||'sin anotar'}{r.partials!==null&&r.partials>0?` · ${r.partials} parciales adicionales`:''}{r.failure?' · intento fallido adicional':''}</p><p>{label(r)}</p><small>{r.date?`Fecha: ${r.date}`:`Semana estimada: ${weekRange(weekDate(r.block,r.week,calendar))}`}</small><details><summary>Ver serie original</summary><p className="original-stat">{r.raw}</p><small>{r.source}</small></details></>}</div>;
}
function SeriesChart({rows,metric,calendar,title}:{rows:Performance[];metric:'weight'|'reps';calendar:CalendarConfig;title:string}) {
  const [selected,setSelected]=useState<string>('');
  const values=rows.map(r=>r[metric]??0);
  const max=Math.max(1,...values),min=Math.min(0,...values);
  const ords=rows.map(r=>Date.parse(performanceDate(r,calendar))/86400000);
  const first=Math.min(...ords),last=Math.max(...ords);
  const points=rows.map((r,i)=>({r,x:first===last?300:35+(ords[i]-first)/(last-first)*530,y:140-((r[metric]??0)-min)/(max-min)*110}));
  const runs:typeof points[]=[];
  for(const point of points){const previous=runs.at(-1);if(previous?.at(-1)?.r.group===point.r.group)previous.push(point);else runs.push([point]);}
  const active=rows.find(r=>r.id===selected)??rows.at(-1);
  return <div className="stat-chart"><h3>{title}</h3>{rows.length?<><svg viewBox="0 0 600 175" role="img" aria-label={title}><text x="0" y="25" fill="#aebc9e" fontSize="12">{n(max)} {metric==='weight'?rows[0].unit:'reps'}</text><line x1="35" y1="140" x2="565" y2="140" stroke="#3b4334"/><g>{runs.map((run,i)=><polyline key={i} points={run.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#c8f36b" strokeWidth="2"/>)}</g>{points.map(({r,x,y})=><circle key={r.id} cx={x} cy={y} r={active?.id===r.id?6:4} fill="#c8f36b" role="button" tabIndex={0} aria-label={`${label(r)}: ${r.weight} ${r.unit}, ${r.reps} repeticiones`} onClick={()=>setSelected(r.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(r.id);}}}><title>{label(r)}: {r.weight===null?'carga sin anotar':`${r.weight} ${r.unit}`} × {r.reps}</title></circle>)}<text x="35" y="166" fill="#aebc9e" fontSize="11">{label(rows[0])}</text>{rows.length>1&&<text x="565" y="166" textAnchor="end" fill="#aebc9e" fontSize="11">{label(rows.at(-1)!)}</text>}</svg><label>Consultar punto<select aria-label="Consultar punto" value={active?.id??''} onChange={e=>setSelected(e.target.value)}>{rows.map(r=><option key={r.id} value={r.id}>{label(r)} · {r[metric]} {metric==='weight'?r.unit:'reps'}</option>)}</select></label>{active&&<p>{label(active)} · {active.weight===null?'Carga sin anotar':`${n(active.weight)} ${active.unit}`} × {active.reps} · RIR {active.rir||'sin anotar'} · {active.date??weekRange(weekDate(active.block,active.week,calendar))}{!active.date&&' (semana estimada)'}</p>}<p className="small-note">Un punto por semana con resultado válido. Las sesiones nuevas usan su fecha registrada. Los huecos sin resultados no se rellenan con cero. Los cambios de equipo se muestran sin unir sus líneas.</p></>:<p>Sin series con esta carga.</p>}</div>;
}
